//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public int id_cancha { get; set; }
        public System.TimeSpan horaInicio { get; set; }
        public System.TimeSpan horaFinal { get; set; }
        public int precio { get; set; }
    
        public virtual Cancha Cancha { get; set; }
    }
}
