

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebProyecto.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ProyectoWeb : DbContext
{
    public ProyectoWeb()
        : base("name=ProyectoWeb")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Cancha> Canchas { get; set; }

    public virtual DbSet<Equipos> Equipos { get; set; }

    public virtual DbSet<Horario> Horarios { get; set; }

    public virtual DbSet<Reto> Retos { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

}

}

