//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<int> telefono { get; set; }
        public string correo { get; set; }
        public string contraseña { get; set; }
        public Nullable<int> equipo_id { get; set; }
        public string Rol { get; set; }
    
        public virtual Equipos Equipos { get; set; }
    }
}
